### ISSUE TITLE
Cannot create document 

### ISSUE THREAD

**Issue by petherin** [kuzzleio/kuzzle-plugin-probe-listener#4]
I'm on MacOS Sierra 10.12.6 on a MacBook Pro (15-inch, 2016)

### Background

I run `docker-compose up` and the Kuzzle KDC container wasn't starting. It reported this error when I ran `docker logs kuzzle-plugin-probe_kdc-kuzzle_1`. 

```
[ℹ] Starting Kuzzle server
[x] [ERROR] Error: Cannot find module 'long-timeout'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/plugins/enabled/kuzzle-plugin-probe/lib/index.js:25:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Object.extManager (/var/app/node_modules/reify/node/compile-hook.js:18:12)
    at Object.manager [as .js] (/var/app/node_modules/reify/node/wrapper.js:108:20)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at PluginsManager.load (/var/app/lib/api/core/plugins/pluginsManager.js:788:29)
    at PluginsManager.init (/var/app/lib/api/core/plugins/pluginsManager.js:82:25)
    at internalEngine.init.then.then.then.then.then.then.then (/var/app/lib/api/kuzzle.js:131:39)
    at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:694:18)
```

I ran `npm install` in the root folder and then `docker-compose up` started working.

### Error
I connected to `http://console.kuzzle.io` and logged into the local instance. I could create an index and collection, but on trying to create a document I got this error:

```
An error occurred while trying to create the document: 
this.client.query is not a function This is probably not a Kuzzle error, but a problem with a plugin implementation.
```

It also happens when creating a document via a web socket connection at the command line. 

For reference, here is the output of `npm version`.

```
➜  kuzzle-plugin-probe git:(master) ✗ npm version
{ 'kuzzle-plugin-probe': '1.0.1',
  npm: '6.7.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.1.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.37.0',
  node: '11.15.0',
  openssl: '1.1.1b',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.27.0',
  v8: '7.0.276.38-node.19',
  zlib: '1.2.11' }
```

**Comment by scottinet** [comment]
Fixed
